#!/bin/env ruby
# encoding: utf-8

#задаём массив сайтов
@sites = ['4mycar.ru','vmolchanov.abcp.ru','training.noda.pro','www.franch.abcp.ru','www.mir.franch.abcp.ru']
#задаём массив страниц
@pages = ['page=catalog','page=catalog&man=16','page=catalog&man=16&model=6414','page=catalog&man=16&model=6414&modelVariant=31960','page=catalog&man=16&model=6414&modelVariant=31960&group=100384',
         'search_type=&pcode=oc90','pbrandnumber=OC90&pbrandname=Knecht','page=carbase','page=carbase&manufacturerId=15','page=carbase&modelId=1207','page=carbase&modificationId=13073',
         'page=goods_catalog&action=search&goods_group=tires','page=goods_catalog&action=search&goods_group=disks','page=goods_info&brand=ABT&number=FCR1985351257DM']

#-----------------------------------------------------------------------------------------------------------------------
#Проверка сервисных cайтов на наличие noindex [tecdoc]
def test3()
  for index1 in 1 ... @sites.size
    for index2 in 0 ... @pages.size
      link = 'http://'+@sites[index1]+'/?'+@pages[index2]
      #переходим по ссылке
      @driver.navigate.to link
      #удаляем все куки
      @driver.manage().delete_all_cookies
      #проверяем наличие noindex, nofollow на странице
      result = @driver.find_elements(:xpath, "//meta[@name='robots' and @content='noindex, nofollow']").count
      if result == 1 then
        puts time+' test3: noindex [tecdoc] присутствует. ссылка: '+link
      else
        puts time+' test3: Ошибка! noindex [tecdoc] отсутствует. ссылка: '+link
      end
    end
  end
end

#-----------------------------------------------------------------------------------------------------------------------
#Проверка 4mycar на отсутствие noindex
def test4()
  for index2 in 0 ... @pages.size
    link = 'http://'+@sites[0]+'/?'+@pages[index2]
    #переходим по ссылке
    @driver.navigate.to link
    #удаляем все куки
    @driver.manage().delete_all_cookies
    #проверяем наличие noindex, nofollow на странице
    result = @driver.find_elements(:xpath, "//meta[@name='robots' and @content='noindex, nofollow']").count
    if result == 0 then
      puts time+' test4: noindex [4mycar] отсутствует. ссылка: '+link
    else
      puts time+' test4: Ошибка! noindex [4mycar] присутствует. ссылка: '+link
    end
  end
end