#!/bin/env ruby
# encoding: utf-8

#Проверки на noindex
def test1()
  #задаём адрес ссылки
  link = "http://4mycar.ru/parts/Febi/01089"

  #переходим по ссылке
  @driver.navigate.to link

  #проверяем наличие noindex в комментариях
=begin
  result = @driver.find_elements(:xpath, "//comment()[contains(.,'noindex')]").count
  puts result
=end

  #проверяем отсутствие noindex в результатах
  begin
    result = @driver.find_elements(:xpath, "//div[@id='searchResultsDiv']//noindex").nil?
  rescue
  end

  if result == false then
    puts time+': noindex в результатах нет'
  else
    puts time+': Ошибка! noindex в результатах есть!'
  end
end

